id: 3d0c44ab73b94c21a0294c05ab5a9cf3
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_211-Teaching_the_Fundamental_Exposition_of_Dependent_Arising-v2
  language: bo
  author: ''
  volume: {}
